<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Glow.Bench</RootNamespace>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Glow.Shared\Glow.Shared.csproj" />
    <ProjectReference Include="..\Glow.Server\Glow.Server.csproj" />
  </ItemGroup>

</Project>
